version: "3.8"

services:
  localstack:
    image: public.ecr.aws/localstack/localstack:3.0
    ports:
      - "4566:4566"   # LocalStack gateway
    environment:
      - SERVICES=s3,lambda,dynamodb,cloudformation,apigateway,iam,cloudwatch
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_PLATFORM=linux/amd64
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-net

networks:
  localstack-net:
    driver: bridge
